name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Chạy hàng ngày lúc nửa đêm
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: duong2024 # Thay 'your-username' bằng username GitHub của bạn
          outputs: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
0
